# © Nicholai Fox Martinsen 2019.
# This computer code is licensed for use solely by the person to whom it is
# delivered and  may not be transferred, duplicated or reverse engineered, or decompiled.

import getpass

keys = {'Apex Legends': {'ADS': '+toggle_zoom" 0',
                 'changegrenade': '+strafe" 0',
                 'Chat': 'say_team" 0',
                 'Crouch': '+duck" 0',
                 'Fire Mode': '+scriptcommand3" 0',
                 'Grenade': 'weaponSelectOrdnance" 0',
                 'Heal': '+scriptCommand4" 0',
                 'Interact': '+use; +use_long" 0',
                 'Inventory': 'toggle_inventory" 0',
                 'Jump': '+jump" 0',
                 'Map': 'toggle_map" 0',
                 'Melee': '+melee" 0',
                 'Move Backward': '+backward" 0',
                 'Move Forward': '+forward" 0',
                 'Move Left': '+moveleft" 0',
                 'Move Right': '+moveright" 0',
                 'Ping': '+ping" 0',
                 'Push-to-Talk': '+pushtotalk" 0',
                 'Reload': '+reload" 0',
                 'Shoot': '+attack" 0',
                 'Sprint': '+speed" 0',
                 'togglecrouch': '+toggle_duck" 0',
                 'Weapon 1': 'weaponSelectPrimary0',
                 'Weapon 2': 'weaponSelectPrimary1',
                 'Weapon 3': None,
                 'Weapon 4': None,
                 'Next Weapon':'+weaponcycle',
                 'Previous Weapon':'+weaponcycle',
                 'Stow Weapons': 'weaponSelectPrimary2',
                 'FOV': 'cl_fovScale',
                 'RESH':'setting.defaultresheight',
                 'RESW':'setting.defaultres',
                 'SENS':'mouse_sensitivity "'},
        'PUBG': {'ADS': 'ActionName="Targeting"',
                 'Chat': None,
                 'Crouch': 'ActionName="ToggleCrouch"',
                 'Fire Mode': 'ActionName="ToggleFiringMode"',
                 'Grenade': 'ActionName="Weapon_5"',
                 'Heal': 'ActionName="UseBandage"',
                 'Interact': 'ActionName="Interact"',
                 'Inventory': 'ActionName="ToggleInventory"',
                 'Jump': 'ActionName="Jump"',
                 'Map': 'ActionName="ToggleMap"',
                 'Melee': None,
                 'Move Backward': 'AxisName="MoveForward",Scale=-1.000000',
                 'Move Forward': 'AxisName="MoveForward",Scale=1.000000',
                 'Move Left': 'AxisName="MoveRight",Scale=-1.000000',
                 'Move Right': 'AxisName="MoveRight",Scale=1.000000',
                 'Ping': None,
                 'Push-to-Talk': 'ActionName="PushToTalk"',
                 'Reload': 'ActionName="Reload"',
                 'Shoot': 'ActionName="Fire"',
                 'Sprint': 'ActionName="Sprint"',
                 'Weapon 1': 'ActionName="Weapon_1"',
                 'Weapon 2': 'ActionName="Weapon_2"',
                 'Weapon 3': 'ActionName="Weapon_3"',
                 'Weapon 4': 'ActionName="Weapon_4"',
                 'Stow Weapons': 'ActionName="Unarm"',
                 'Next Weapon':'+weaponcycle',
                 'Previous Weapon':'+weaponcycle',
                 'ActionName="VehicleBoost"': 'ActionName="VehicleBoost"',
                 'vmoveback': 'AxisName="VehicleMoveForward",Scale=-1.000000',
                 'vmoveforward': 'AxisName="VehicleMoveForward",Scale=1.000000',
                 'vmoveright': 'AxisName="VehicleMoveRight",Scale=1.000000',
                 'vmoveleft': 'AxisName="VehicleMoveRight",Scale=-1.000000',
                 'FOV': 'FpsCameraFov=',
                 'RESH':'ResolutionSizeY=',
                 'RESW':'ResolutionSizeX=',
                 'SENS':'SensitiveName="Normal",Sensitivity='},
        'CS:GO': {'ADS': 'ActionName="Targeting"'}
                 }

# with open('configtranslations\\PUBG.txt', 'r') as file:
#     x =file.read()
#     x = x.replace("'", '')
#     with open('configtranslations\\PUBG.txt', 'w') as file:
#         file.write(x)


offsets = {"Apex Legends": -1
    , "PUBG": 8,
           "CS:GO": -1}

fovoffset = {"Apex Legends":13,
             'PUBG':13,
             'CS:GO':15}

resoffset={"Apex Legends":{'w':23,'h':29},
             'PUBG':{'w':16, 'h':16},
           'CS:GO':{'w':23,'h':29}
           }

numberlist = ['1','2','3','4','5','6','7','8','9','0','.']

direction = {"Apex Legends": -1,
             "PUBG": 1,
             'CS:GO':-1}

bindinglines = {'Apex':{
                 '+toggle_zoom':'bind_US_standard "" "+toggle_zoom" 0',
                 '+strafe':'bind_held_US_standard "" "+strafe" 0',
                 'say_team':'bind_US_standard "" "say_team" 0',
                 '+duck':'bind_US_standard "" "+duck" 0',
                 '+scriptcommand3':'bind_US_standard "" "+scriptcommand3" 0',
                 'weaponSelectOrdnance':'bind_US_standard "" "weaponSelectOrdnance" 0',
                 '+scriptCommand4':'bind_US_standard "" "+scriptCommand4" 0',
                 '+use; +use_long':'bind_US_standard "" "+use; +use_long" 0',
                 'toggle_inventory" 0':'bind_US_standard "" "toggle_inventory" 0',
                 '+jump':'bind_US_standard "" "+toggle_zoom" 0',
                 'toggle_map':'bind_US_standard "" "toggle_map" 0',
                 '+melee':'bind_US_standard "" "+melee" 0',
                 '+backward':'bind_US_standard "" "+backward" 0',
                 '+forward':'bind_US_standard "" "+forward" 0',
                 '+moveleft':'bind_US_standard "" "+moveleft" 0',
                 '+moveright':'bind_US_standard "" "+moveright" 0',
                 '+ping':'bind_US_standard "" "+ping" 0',
                 '+pushtotalk':'bind_US_standard "" "+pushtotalk" 0',
                 '+reload':'bind_US_standard "" "+reload" 0',
                 '+attack':'bind_US_standard "" "+attack" 0',
                 '+speed':'bind_US_standard "" "+speed" 0',
                 '+toggle_duck':'bind_US_standard "" "+toggle_duck" 0',
                 'weaponSelectPrimary0':'bind_US_standard "" "weaponSelectPrimary0" 0',
                 'weaponSelectPrimary1':'bind_US_standard "" "weaponSelectPrimary1" 0',
                 'weaponSelectPrimary2':'bind_US_standard "" "weaponSelectPrimary2" 0'},
        'Pubg':{
                 'ActionName="Targeting"': '(ActionName="Targeting",Keys=((Key=RightMouseButton),())),',
                 'ActionName="ToggleCrouch"': '(ActionName="ToggleCrouch",Keys=((Key=C),())),',
                 'ActionName="ToggleFiringMode"': '(ActionName="ToggleFiringMode",Keys=((Key=B),())),',
                 'ActionName="Weapon_5"': '(ActionName="Weapon_5",Keys=((Key=Five),())),',
                 'ActionName="UseBandage"': '(ActionName="UseBandage",Keys=((Key=Nine),())),',
                 'ActionName="Interact"': '(ActionName="Interact",Keys=((Key=F),())),',
                 'ActionName="ToggleInventory"': '(ActionName="ToggleInventory",Keys=((Key=Tab),())),',
                 'ActionName="Jump"': '(ActionName="Jump",Keys=((Key=SpaceBar),())),',
                 'ActionName="ToggleMap"': '(ActionName="ToggleMap",Keys=((Key=M),())),',
                 'AxisName="MoveForward",Scale=-1.000000': '(AxisName="MoveForward",Scale=-1.000000,Keys=((Key=S),())),',
                 'AxisName="MoveForward",Scale=1.000000': '(AxisName="MoveForward",Scale=1.000000,Keys=((Key=W),())),',
                 'AxisName="MoveRight",Scale=-1.000000': '(AxisName="MoveRight",Scale=-1.000000,Keys=((Key=A),())),',
                 'AxisName="MoveRight",Scale=1.000000': '(AxisName="MoveRight",Scale=1.000000,Keys=((Key=D),())),',
                 'ActionName="PushToTalk"': '(ActionName="PushToTalk",Keys=((),())),',
                 'ActionName="Reload"': '(ActionName="Reload",Keys=((Key=R),())),',
                 'ActionName="Fire"': '(ActionName="Fire",Keys=((Key=LeftMouseButton),())),',
                 'ActionName="Sprint"': '(ActionName="Sprint",Keys=((Key=LeftShift),())),',
                 'ActionName="Weapon_1"': '(ActionName="Weapon_1",Keys=((Key=One),())),',
                 'ActionName="Weapon_2"': '(ActionName="Weapon_2",Keys=((Key=Two),())),',
                 'ActionName="Weapon_3': '(ActionName="Weapon_3",Keys=((Key=Three),())),',
                 'ActionName="Weapon_4': '(ActionName="Weapon_4",Keys=((Key=Four),())),',
                 'ActionName="Unarm"': '(ActionName="Unarm",Keys=((Key=X),())),',
                 'ActionName="VehicleBoost"': '(ActionName="VehicleBoost",Keys=((Key=LeftShift),())),',
                 'AxisName="VehicleMoveForward",Scale=-1.000000': '(AxisName="VehicleMoveForward",Scale=-1.000000,Keys=((Key=S),())),',
                 'AxisName="VehicleMoveForward",Scale=1.000000': '(AxisName="VehicleMoveForward",Scale=1.000000,Keys=((Key=W),())),',
                 'AxisName="VehicleMoveRight",Scale=1.000000': '(AxisName="VehicleMoveRight",Scale=1.000000,Keys=((Key=D),())),',
                 'AxisName="VehicleMoveRight",Scale=-1.000000': '(AxisName="VehicleMoveRight",Scale=-1.000000,Keys=((Key=A),())),',
                 'ActionName="Walk"': '(ActionName="Walk",Keys=((),()))'}
}

user = getpass.getuser()

yaw = {'Apex Legends': 0.022,
       'PUBG': 0.000883676,
       'CS:GO': 0.022}

maxfov = {'Apex Legends': 1.7,
          'PUBG':103,
          'CS:GO':68}

minfov = {'Apex Legends': 1,
          'PUBG':80,
          'CS:GO':50}

labeldisplay = {
'0': '0',
'1': '1',
'2': '2',
'3': '3',
'4': '4',
'5': '5',
'6': '6',
'7': '7',
'8': '8',
'9': '9',
'A': 'A',
'Add': 'NUMPAD +',
'B': 'B',
'Back': 'BACKSPACE',
'C': 'C',
'Capital': 'CAPS LOCK',
'D': 'D',
'Decimal': 'NUMPAD .',
'Delete': 'DEL',
'Divide': 'NUMPAD /',
'Down': 'DOWN ARROW',
'E': 'E',
'End': 'END',
'F': 'F',
'F1': 'F1',
'F10': 'F10',
'F11': 'F11',
'F12': 'F12',
'F2': 'F2',
'F3': 'F3',
'F4': 'F4',
'F5': 'F5',
'F6': 'F6',
'F7': 'F7',
'F8': 'F8',
'F9': 'F9',
'G': 'G',
'H': 'H',
'Home': 'HOME',
'I': 'I',
'Insert': 'INSERT',
'J': 'J',
'K': 'K',
'L': 'L',
'Lcontrol': 'LCTRL',
'Left': 'LEFT ARROW',
'Lmenu': 'LALT',
'Lshift': 'LSHIFT',
'M': 'M',
'Multiply': 'NUMPAD *',
'N': 'N',
'Next': 'PAGE DOWN',
'Numlock': 'NUMLOCK',
'Numpad0': 'NUMPAD 0',
'Numpad1': 'NUMPAD 1',
'Numpad2': 'NUMPAD 2',
'Numpad3': 'NUMPAD 3',
'Numpad4': 'NUMPAD 4',
'Numpad5': 'NUMPAD 5',
'Numpad6': 'NUMPAD 6',
'Numpad7': 'NUMPAD 7',
'Numpad8': 'NUMPAD 8',
'Numpad9': 'NUMPAD 9',
'O': 'O',
'Oem_1': ';',
'Oem_2': '/',
'Oem_3': '`',
'Oem_4': '[',
'Oem_5': '\\',
'Oem_6': ']',
'Oem_7': "'",
'Oem_Comma': ',',
'Oem_Minus': '-',
'Oem_Period': '.',
'Oem_Plus': '=',
'P': 'P',
'Pause': 'PAUSE',
'Prior': 'PAGE UP',
'Q': 'Q',
'R': 'R',
'Rcontrol': 'RCTRL',
'Return': 'ENTER',
'Right': 'RIGHT ARROW',
'Rmenu': 'RALT',
'Rshift': 'RSHIFT',
'S': 'S',
'Scroll': 'SCROLL LOCK',
'Space': 'SPACE',
'Subtract': 'NUMPAD -',
'T': 'T',
'Tab': 'TAB',
'U': 'U',
'Up': 'UP ARROW',
'V': 'V',
'W': 'W',
'X': 'X',
'Y': 'Y',
'Z': 'Z',
'LEFT CLICK': 'LEFT CLICK',
'RIGHT CLICK': 'RIGHT CLICK',
'SCROLL CLICK': 'SCROLL CLICK',
'MOUSE BUTTON 4': 'MOUSE BUTTON 4',
'MOUSE BUTTON 5': 'MOUSE BUTTON 5',
'MOUSE WHEEL': 'MOUSE WHEEL DOWN',
'MOUSE WHEEL 123': 'MOUSE WHEEL UP',
'': ''}

# 'F1': ,
# 'F2': ,
# 'F3': ,
# 'F4': ,
# 'F5': ,
# 'F6': ,
# 'F7': ,
# 'F8': ,
# 'F9': ,
# 'F10': ,
# 'F11': ,
# 'F12': ,
# 'Scroll': ,
# 'Pause': ,
# 'Oem_3': ,
# '1': ,
# '2': ,
# '3': ,
# '4': ,
# '5': ,
# '6': ,
# '7': ,
# '8': ,
# '9': ,
# '0': ,
# 'Oem_Minus': ,
# 'Oem_Plus': ,
# 'Back': ,
# 'Insert': ,
# 'Home': ,
# 'Prior': ,
# 'Numlock': ,
# 'Divide': ,
# 'Multiply': ,
# 'Subtract': ,
# 'Tab': ,
# 'Q': ,
# 'W': ,
# 'E': ,
# 'R': ,
# 'T': ,
# 'Y': ,
# 'U': ,
# 'I': ,
# 'O': ,
# 'P': ,
# 'Oem_4': ,
# 'Oem_6': ,
# 'Oem_5': ,
# 'Delete': ,
# 'End': ,
# 'Next': ,
# 'Numpad7': ,
# 'Numpad8': ,
# 'Numpad9': ,
# 'Add': ,
# 'Capital': ,
# 'A': ,
# 'S': ,
# 'D': ,
# 'F': ,
# 'G': ,
# 'H': ,
# 'J': ,
# 'K': ,
# 'L': ,
# 'Oem_1': ,
# 'Oem_7': ,
# 'Return': ,
# 'Numpad4': ,
# 'Numpad5': ,
# 'Numpad6': ,
# 'Lshift': ,
# 'Z': ,
# 'X': ,
# 'C': ,
# 'V': ,
# 'B': ,
# 'N': ,
# 'M': ,
# 'Oem_Comma': ,
# 'Oem_Period': ,
# 'Oem_2': ,
# 'Rshift': ,
# 'Up':,
# 'Numpad1': ,
# 'Numpad2': ,
# 'Numpad3': ,
# 'Lcontrol': ,
# 'Lwin': ,
# 'Lmenu': ,
# 'Space': ,
# 'Rmenu': ,
# 'Rwin': ,
# 'Apps': ,
# 'Rcontrol': ,
# 'Left': ,
# 'Down': ,
# 'Right': ,
# 'Numpad0': ,
# 'Decimal': ,
